<a href="https://colab.research.google.com/github/Arunav07/CRISTL-Project-1/blob/Atharva_D's-Branch/tf.data_success_with_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [3]:
df = pd.read_csv("/content/drive/MyDrive/IDD_Detection/matrix.csv")

In [4]:
df

Labels  truck  person  ...  vehicle fallback  traffic sign  animal
0   Encodings      1       1  ...                 0             0       0
1        xmin     26     708  ...                 0             0       0
2        ymin    293     439  ...                 0             0       0
3        xmax    396     754  ...                 0             0       0
4        ymax    604     480  ...                 0             0       0
5      Labels  truck  person  ...  vehicle fallback  traffic sign  animal
6   Encodings      1       1  ...                 0             0       0
7        xmin    633     985  ...                 0             0       0
8        ymin    391     448  ...                 0             0       0
9        xmax    660    1030  ...                 0             0       0
10       ymax     42     579  ...                 0             0       0
11     Labels  truck  person  ...  vehicle fallback  traffic sign  animal
12  Encodings      1       0  ...                 0             0       0
13       xmin    617       0  ...                 0             0       0
14       ymin    385       0  ...                 0             0       0
15       xmax    653       0  ...                 0             0       0
16       ymax    425       0  ...                 0             0       0
17     Labels  truck  person  ...  vehicle fallback  traffic sign  animal
18  Encodings      1       1  ...                 0             0       0
19       xmin     92     804  ...                 0             0       0
20       ymin    354     505  ...                 0             0       0
21       xmax    456     843  ...                 0             0       0
22       ymax    653     535  ...                 0             0       0
23     Labels  truck  person  ...  vehicle fallback  traffic sign  animal
24  Encodings      1       0  ...                 0             0       0
25       xmin    662       0  ...                 0             0       0
26       ymin    379       0  ...                 0             0       0
27       xmax    689       0  ...                 0             0       0
28       ymax    414       0  ...                 0             0       0
29     Labels  truck  person  ...  vehicle fallback  traffic sign  animal
30  Encodings      1       0  ...                 0             0       0
31       xmin    633       0  ...                 0             0       0
32       ymin    390       0  ...                 0             0       0
33       xmax    654       0  ...                 0             0       0
34       ymax    424       0  ...                 0             0       0
35     Labels  truck  person  ...  vehicle fallback  traffic sign  animal
36  Encodings      1       0  ...                 0             0       0
37       xmin    647       0  ...                 0             0       0
38       ymin    370       0  ...                 0             0       0
39       xmax    675       0  ...                 0             0       0
40       ymax    408       0  ...                 0             0       0
41     Labels  truck  person  ...  vehicle fallback  traffic sign  animal
42  Encodings      1       1  ...                 0             0       0
43       xmin    619     681  ...                 0             0       0
44       ymin    376     400  ...                 0             0       0
45       xmax    657     691  ...                 0             0       0
46       ymax    434     428  ...                 0             0       0
47     Labels  truck  person  ...  vehicle fallback  traffic sign  animal
48  Encodings      1       1  ...                 0             0       0
49       xmin    588     666  ...                 0             0       0
50       ymin    388     413  ...                 0             0       0
51       xmax    644     681  ...                 0             0       0
52       ymax    449     447  ...                 0             0       0
53     Labe

In [5]:
vals = df.values
vals

array([['Encodings', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0',
        '0'],
       ['xmin', '26', '708', '999', '131', '0', '0', '0', '0', '0', '0',
        '0'],
       ['ymin', '293', '439', '414', '468', '0', '0', '0', '0', '0', '0',
        '0'],
       ['xmax', '396', '754', '1132', '1277', '0', '0', '0', '0', '0',
        '0', '0'],
       ['ymax', '604', '480', '541', '963', '0', '0', '0', '0', '0', '0',
        '0'],
       ['Labels', 'truck', 'person', 'autorickshaw', 'car', 'motorcycle',
        'rider', 'bus', 'bicycle', 'vehicle fallback', 'traffic sign',
        'animal'],
       ['Encodings', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0',
        '0'],
       ['xmin', '633', '985', '686', '0', '0', '0', '0', '0', '0', '0',
        '0'],
       ['ymin', '391', '448', '410', '0', '0', '0', '0', '0', '0', '0',
        '0'],
       ['xmax', '660', '1030', '705', '0', '0', '0', '0', '0', '0', '0',
        '0'],
       ['ymax', '42', '579', '427', '0', '0', '0', '0'

In [6]:
vals_list = vals.tolist()
vals_list

[['Encodings', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0'],
 ['xmin', '26', '708', '999', '131', '0', '0', '0', '0', '0', '0', '0'],
 ['ymin', '293', '439', '414', '468', '0', '0', '0', '0', '0', '0', '0'],
 ['xmax', '396', '754', '1132', '1277', '0', '0', '0', '0', '0', '0', '0'],
 ['ymax', '604', '480', '541', '963', '0', '0', '0', '0', '0', '0', '0'],
 ['Labels',
  'truck',
  'person',
  'autorickshaw',
  'car',
  'motorcycle',
  'rider',
  'bus',
  'bicycle',
  'vehicle fallback',
  'traffic sign',
  'animal'],
 ['Encodings', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0'],
 ['xmin', '633', '985', '686', '0', '0', '0', '0', '0', '0', '0', '0'],
 ['ymin', '391', '448', '410', '0', '0', '0', '0', '0', '0', '0', '0'],
 ['xmax', '660', '1030', '705', '0', '0', '0', '0', '0', '0', '0', '0'],
 ['ymax', '42', '579', '427', '0', '0', '0', '0', '0', '0', '0', '0'],
 ['Labels',
  'truck',
  'person',
  'autorickshaw',
  'car',
  'motorcycle',
  'rider',
  'bus',
  'bicycle'

In [7]:
L = [['Encodings', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0'],
 ['xmin', '26', '708', '999', '131', '0', '0', '0', '0', '0', '0', '0'],
 ['ymin', '293', '439', '414', '468', '0', '0', '0', '0', '0', '0', '0'],
 ['xmax', '396', '754', '1132', '1277', '0', '0', '0', '0', '0', '0', '0'],
 ['ymax', '604', '480', '541', '963', '0', '0', '0', '0', '0', '0', '0'],
 ['Labels',
  'truck',
  'person',
  'autorickshaw',
  'car',
  'motorcycle',
  'rider',
  'bus',
  'bicycle',
  'vehicle fallback',
  'traffic sign',
  'animal']]

In [8]:
Arr = np.array(L)
Arr

array([['Encodings', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0',
        '0'],
       ['xmin', '26', '708', '999', '131', '0', '0', '0', '0', '0', '0',
        '0'],
       ['ymin', '293', '439', '414', '468', '0', '0', '0', '0', '0', '0',
        '0'],
       ['xmax', '396', '754', '1132', '1277', '0', '0', '0', '0', '0',
        '0', '0'],
       ['ymax', '604', '480', '541', '963', '0', '0', '0', '0', '0', '0',
        '0'],
       ['Labels', 'truck', 'person', 'autorickshaw', 'car', 'motorcycle',
        'rider', 'bus', 'bicycle', 'vehicle fallback', 'traffic sign',
        'animal']], dtype='<U16')

In [9]:
Matrix = np.asmatrix(Arr)
Matrix

matrix([['Encodings', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0',
         '0'],
        ['xmin', '26', '708', '999', '131', '0', '0', '0', '0', '0', '0',
         '0'],
        ['ymin', '293', '439', '414', '468', '0', '0', '0', '0', '0',
         '0', '0'],
        ['xmax', '396', '754', '1132', '1277', '0', '0', '0', '0', '0',
         '0', '0'],
        ['ymax', '604', '480', '541', '963', '0', '0', '0', '0', '0',
         '0', '0'],
        ['Labels', 'truck', 'person', 'autorickshaw', 'car',
         'motorcycle', 'rider', 'bus', 'bicycle', 'vehicle fallback',
         'traffic sign', 'animal']], dtype='<U16')

In [10]:
arr = df.to_numpy()
arr

array([['Encodings', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0',
        '0'],
       ['xmin', '26', '708', '999', '131', '0', '0', '0', '0', '0', '0',
        '0'],
       ['ymin', '293', '439', '414', '468', '0', '0', '0', '0', '0', '0',
        '0'],
       ['xmax', '396', '754', '1132', '1277', '0', '0', '0', '0', '0',
        '0', '0'],
       ['ymax', '604', '480', '541', '963', '0', '0', '0', '0', '0', '0',
        '0'],
       ['Labels', 'truck', 'person', 'autorickshaw', 'car', 'motorcycle',
        'rider', 'bus', 'bicycle', 'vehicle fallback', 'traffic sign',
        'animal'],
       ['Encodings', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0',
        '0'],
       ['xmin', '633', '985', '686', '0', '0', '0', '0', '0', '0', '0',
        '0'],
       ['ymin', '391', '448', '410', '0', '0', '0', '0', '0', '0', '0',
        '0'],
       ['xmax', '660', '1030', '705', '0', '0', '0', '0', '0', '0', '0',
        '0'],
       ['ymax', '42', '579', '427', '0', '0', '0', '0'

In [11]:
arr.shape

(59, 12)

In [12]:
matx = np.asmatrix(arr)
matx

matrix([['Encodings', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0',
         '0'],
        ['xmin', '26', '708', '999', '131', '0', '0', '0', '0', '0', '0',
         '0'],
        ['ymin', '293', '439', '414', '468', '0', '0', '0', '0', '0',
         '0', '0'],
        ['xmax', '396', '754', '1132', '1277', '0', '0', '0', '0', '0',
         '0', '0'],
        ['ymax', '604', '480', '541', '963', '0', '0', '0', '0', '0',
         '0', '0'],
        ['Labels', 'truck', 'person', 'autorickshaw', 'car',
         'motorcycle', 'rider', 'bus', 'bicycle', 'vehicle fallback',
         'traffic sign', 'animal'],
        ['Encodings', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0',
         '0'],
        ['xmin', '633', '985', '686', '0', '0', '0', '0', '0', '0', '0',
         '0'],
        ['ymin', '391', '448', '410', '0', '0', '0', '0', '0', '0', '0',
         '0'],
        ['xmax', '660', '1030', '705', '0', '0', '0', '0', '0', '0', '0',
         '0'],
        ['ymax', '42', '579', '42

In [13]:
L=np.asarray(L)
L.shape

(6, 12)

In [14]:
La=pd.read_excel("/content/drive/MyDrive/matrix.xlsx")
La


Labels  truck  person  ...  vehicle fallback  traffic sign   animal
0  Encodings      1       1  ...                 0              0       0
1       xmin     26     708  ...                 0              0       0
2       ymin    293     439  ...                 0              0       0
3       xmax    396     754  ...                 0              0       0
4       ymax    604     480  ...                 0              0       0

[5 rows x 12 columns]

In [15]:
vals = La.values
vals

array([['Encodings', 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       ['xmin', 26, 708, 999, 131, 0, 0, 0, 0, 0, 0, 0],
       ['ymin', 293, 439, 414, 468, 0, 0, 0, 0, 0, 0, 0],
       ['xmax', 396, 754, 1132, 1277, 0, 0, 0, 0, 0, 0, 0],
       ['ymax', 604, 480, 541, 963, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [16]:
matrix=[[ 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
        [26, 708, 999, 131, 0, 0, 0, 0, 0, 0, 0],
        [293, 439, 414, 468, 0, 0, 0, 0, 0, 0, 0],
        [396, 754, 1132, 1277, 0, 0, 0, 0, 0, 0, 0],
        [604, 480, 541, 963, 0, 0, 0, 0, 0, 0, 0]]

In [17]:
Label=[]
Label.append(matrix)
len(Label)

1

In [18]:
Label=np.asarray(Label)
Label.shape

(1, 5, 11)

In [19]:
Image_array=[]
Image=tf.io.read_file("/content/drive/MyDrive/IDD_Detection/JPEGImages/frontFar/BLR-2018-03-22_17-39-26_2_frontFar/0000060.jpg")
im_decoded = tf.io.decode_jpeg(Image) 
img=tf.image.rgb_to_grayscale(im_decoded)
img = tf.image.central_crop(img, 0.85)
img = tf.image.resize(img, size=(256, 256))
img = np.asarray(img)
Image_array.append(img)

In [20]:
print(Image_array)
print(len(Image_array))

[array([[[255.      ],
        [255.      ],
        [255.      ],
        ...,
        [255.      ],
        [255.      ],
        [254.43848 ]],

       [[255.      ],
        [255.      ],
        [255.      ],
        ...,
        [255.      ],
        [255.      ],
        [254.88574 ]],

       [[255.      ],
        [255.      ],
        [255.      ],
        ...,
        [253.98438 ],
        [254.43066 ],
        [254.00586 ]],

       ...,

       [[ 69.68457 ],
        [ 60.71582 ],
        [ 51.19043 ],
        ...,
        [ 73.30957 ],
        [ 78.01074 ],
        [ 75.336914]],

       [[ 82.67578 ],
        [ 75.51465 ],
        [ 56.874023],
        ...,
        [ 77.03711 ],
        [ 80.31445 ],
        [ 75.83887 ]],

       [[ 73.02637 ],
        [ 73.85547 ],
        [ 69.32715 ],
        ...,
        [ 74.52734 ],
        [ 80.21875 ],
        [ 74.95117 ]]], dtype=float32)]
1


In [21]:
Image_array=np.asarray(Image_array)
Image_array.shape

(1, 256, 256, 1)

In [22]:
Image_array=tf.convert_to_tensor(
    Image_array, dtype=None, dtype_hint=None, name=None
)

In [23]:
Label=tf.convert_to_tensor(
    Label, dtype=None, dtype_hint=None, name=None
)

In [24]:
dataset = tf.data.Dataset.from_tensor_slices((Label, Image_array))
print(dataset)

<TensorSliceDataset shapes: ((5, 11), (256, 256, 1)), types: (tf.int64, tf.float32)>


In [30]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder


In [31]:
data=np.asarray([['truck'],['person'],['autorickshaw'],['car'],['motorcycle'],['rider'],['bus'],['bicycle'],['vehicle fallback'],['traffic'],['sign'],['animal']])

In [29]:
# print(data)
# # define ordinal encoding
# encoder = OrdinalEncoder()
# # transform data
# result = encoder.fit_transform(data)
# print(result)

[['truck']
 ['person']
 ['autorickshaw']
 ['car']
 ['motorcycle']
 ['rider']
 ['bus']
 ['bicycle']
 ['vehicle fallback']
 ['traffic']
 ['sign']
 ['animal']]
[[10.]
 [ 6.]
 [ 1.]
 [ 4.]
 [ 5.]
 [ 7.]
 [ 3.]
 [ 2.]
 [11.]
 [ 9.]
 [ 8.]
 [ 0.]]


In [32]:

print(data)
# define one hot encoding
encoder = OneHotEncoder(sparse=False)
# transform data
onehot = encoder.fit_transform(data)
print(onehot)

[['truck']
 ['person']
 ['autorickshaw']
 ['car']
 ['motorcycle']
 ['rider']
 ['bus']
 ['bicycle']
 ['vehicle fallback']
 ['traffic']
 ['sign']
 ['animal']]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
matrix_new=[[ (0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.),(0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.),(0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.),(0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.), 0, 0, 0, 0, 0, 0, 0],
        [26, 708, 999, 131, 0, 0, 0, 0, 0, 0, 0],
        [293, 439, 414, 468, 0, 0, 0, 0, 0, 0, 0],
        [396, 754, 1132, 1277, 0, 0, 0, 0, 0, 0, 0],
        [604, 480, 541, 963, 0, 0, 0, 0, 0, 0, 0]]

SyntaxError: ignored

In [36]:
label_matrix_for_image_1=[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.],[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.],[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

SyntaxError: ignored

In [38]:
La

Labels  truck  person  ...  vehicle fallback  traffic sign   animal
0  Encodings      1       1  ...                 0              0       0
1       xmin     26     708  ...                 0              0       0
2       ymin    293     439  ...                 0              0       0
3       xmax    396     754  ...                 0              0       0
4       ymax    604     480  ...                 0              0       0

[5 rows x 12 columns]

In [39]:
print(La[2][2])

KeyError: ignored

In [40]:
Lab=pd.read_excel("/content/drive/MyDrive/Copy of matrix.xlsx")
Lab

Labels                                  truck  ... traffic sign  animal
0  Encodings  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]  ...             0      0
1       xmin                                     26  ...             0      0
2       ymin                                    293  ...             0      0
3       xmax                                    396  ...             0      0
4       ymax                                    604  ...             0      0

[5 rows x 12 columns]

In [42]:
Lab.values

array([['Encodings', '[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]',
        '[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]',
        '[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]',
        '[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]', 0, 0, 0, 0, 0, 0, 0],
       ['xmin', 26, 708, 999, 131, 0, 0, 0, 0, 0, 0, 0],
       ['ymin', 293, 439, 414, 468, 0, 0, 0, 0, 0, 0, 0],
       ['xmax', 396, 754, 1132, 1277, 0, 0, 0, 0, 0, 0, 0],
       ['ymax', 604, 480, 541, 963, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [43]:
mat=[['[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]',
        '[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]',
        '[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]',
        '[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]', 0, 0, 0, 0, 0, 0, 0],
       [26, 708, 999, 131, 0, 0, 0, 0, 0, 0, 0],
       [293, 439, 414, 468, 0, 0, 0, 0, 0, 0, 0],
       [396, 754, 1132, 1277, 0, 0, 0, 0, 0, 0, 0],
       [604, 480, 541, 963, 0, 0, 0, 0, 0, 0, 0]]

In [46]:
Label=[]
Label.append(matrix)

In [50]:
Label_array=np.asarray(Label)
Label_array.shape

(1, 5, 11)

In [49]:
df = tf.data.Dataset.from_tensor_slices((Label_array, Image_array))
print(df)

<TensorSliceDataset shapes: ((5, 11), (256, 256, 1)), types: (tf.int64, tf.float32)>
